MovieStore/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using MovieStore.ViewModels;
using MovieStore.Repositories;
using MovieStore.Data;
using MovieStore.Enryption;
using MovieStore.Models;
using Newtonsoft.Json;

namespace MovieStore.Controllers
{
    public class CustomerController : Controller
    {

        private readonly ICustomerRepo _customerRepo;
        public CustomerController(ICustomerRepo customerRepo)
        {
            _customerRepo = customerRepo;
        }
        public IActionResult Index()
        {
            var membershipTypes=_customerRepo.GetMembershipTypes();
            var customers=_customerRepo.GetCustomers().ToList();
            var customerViewModel = new CustomerViewModel
            {
                
                MembershipTypes = membershipTypes
            };
            return View(customerViewModel);
        }

        public ActionResult CustomerForm(CustomerViewModel customerViewModel) 
        {
           customerViewModel.MembershipTypes= _customerRepo.GetMembershipTypes();
            //customerViewModel.Customer = new Models.Customer();
            return View(customerViewModel); 
        }

        public PartialViewResult ViewCustomerPartial(int id)
        {
            var customer=_customerRepo.GetCustomer(id);

            var customerViewModel = new CustomerViewModel {
                Customer= customer,
                Name = customer.Name,
                IsSubscribedToNewsLetter = customer.IsSubscribedToNewsLetter,
                MembershipTypeId = customer.MembershipTypeId,
                BirthDate = customer.BirthDate.Value.ToString("dd/MM/yyyy")
                };
            
            return PartialView(customerViewModel);
        }
        public ActionResult Save(Customer customer)
        {
             _customerRepo.AddCustomer(customer);
            //var decryptValue = Utility.DecryptStringAES(_data);
            //var customerr = JsonConvert.DeserializeObject<Customer>(decryptValue);

            return Ok(customer);
        }

        public ActionResult Create()
        {

           return RedirectToAction("Index");
        }

        public ActionResult GetCustomer()
        {
            var customers = _customerRepo.GetCustomers().ToList();
            var json = System.Text.Json.JsonSerializer.Serialize(customers);
            var model = JsonConvert.DeserializeObject<List<CustomerViewModel>>(json);
            foreach (var customer in model)
            {
                var d = Convert.ToDateTime(customer.BirthDate);
                customer.BirthDate = d.ToString("dd/MM/yyyy");
            }
            return Json(model);
        }

        public ActionResult DeleteCustomer(int id)
        {

            var customerDeleted= _customerRepo.DeleteCustomer(id);

            if (customerDeleted)
                return Ok();

            return BadRequest();

        }

    }
}

MovieStore/Controllers/MovieController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MovieStore.Models;
using MovieStore.Repositories;
using MovieStore.ViewModels;
using Newtonsoft.Json;
using System.Text.Json;

namespace MovieStore.Controllers
{
    public class MovieController : Controller
    {
        private readonly IMovieRepo _movieRepo;

        public MovieController(IMovieRepo movieRepo)
        {
            _movieRepo=movieRepo;
        }
        public IActionResult Index()
        {
            var genre = _movieRepo.GetGenres();
            var movieViewModel = new MovieViewModel
            {
                Genres = genre
            };

            ViewBag.GenreId = new SelectList(_movieRepo.GetGenres(), "Id", "Name");
            return View(movieViewModel);
        }

        public PartialViewResult MovieFormPartial()
        {
            var genre = _movieRepo.GetGenres();
            var movieViewModel = new MovieViewModel
            {
                Genres = genre
            };

            ViewBag.GenreId = new SelectList(_movieRepo.GetGenres(),"Id","Name");
            return PartialView(movieViewModel);
        }

        public JsonResult Save(Movie movie)
        {

           var result= _movieRepo.AddMovie(movie);

            if (result == 1)
                return Json("Save Succesfully");
            else
                return Json("Movie not saved");
        }

        public  ActionResult GetMovies()
        {
            var movies= _movieRepo.GetMovies().ToList();

            var json = System.Text.Json.JsonSerializer.Serialize(movies);

            var model = JsonConvert.DeserializeObject<List<MovieViewModel>>(json);
            foreach (var movie in model)
            {
                var d =Convert.ToDateTime(movie.DateAdded);
                movie.DateAdded=d.ToString("dd/MM/yyyy");
            }

            return Json(model);
        }
    }
}

MovieStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieStore</title>
@*    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@ 
    <link rel="stylesheet" href="~/css/bootstrap_flatly.min.css" />

   <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MovieStore.styles.css" asp-append-version="true" />

<!--Data Table-->
<link href="//cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css" rel="stylesheet" type="text/css">


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MovieStore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Customer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="Index">Movie</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MovieStore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <!--Jquery-->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <!--DataTable-->
    <script src="//cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
@*    <script src="~/lib/jquery/dist/jquery.js"></script>*@
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

MovieStore/Views/Shared/_NewLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieStore</title>
@*    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link rel="stylesheet" href="~/css/bootstrap_flatly.min.css" />

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MovieStore.styles.css" asp-append-version="true" />

    <!--Data Table-->
<link href="//cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css" rel="stylesheet" type="text/css">
<!--Toastr-->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css" integrity="sha512-3pIirOrwegjM6erE5gPSwkUzO+3cTjpnV9lexlNZqvupR64iZBnOOTiiLPb9M36zpMScbmUNIcHUqKD47M719g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href=~/lib/toastr/toastr.css />

<link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/sweetalert2@10.10.1/dist/sweetalert2.min.css'>

</head>
<body>
    <header>
@*        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
           <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MovieStore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Customer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="Index">Movie</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
*@ 
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
 <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MovieStore</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav me-auto">
        <li class="nav-item active">
            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Customer</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="Index">Movie</a>
        </li>
@*        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Separated link</a>
          </div>
        </li>*@
      </ul>
      <partial name="_LoginPartial" />
@*      <form class="d-flex">
        <input class="form-control me-sm-2" type="text" placeholder="Search">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
      </form>*@
    </div>
  </div>
</nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MovieStore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src=~/lib/toastr/toastr.js></script>


<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <!--DataTable-->
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.js"></script>
<!--AES Algorithm-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.2/rollups/aes.js"></script>

<!--Toastr -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    @await RenderSectionAsync("Scripts", required: true)

</body>
</html>